tests: pass flags directly instead of borrowing
Fixes the following clippy errors:

error: the borrowed expression implements the required traits
   --> src/lib.rs:219:21
    |
219 |         p.set_flags(&initial).unwrap();
    |                     ^^^^^^^^ help: change this to: `initial`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow
    = note: `-D clippy::needless-borrow` implied by `-D warnings`

error: the borrowed expression implements the required traits
   --> src/lib.rs:224:21
    |
224 |         f.set_flags(&initial).unwrap();
    |                     ^^^^^^^^ help: change this to: `initial`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrow